<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Galaxy.Domain" Version="1.0.2-rc11" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LCMS.Utility\LCMS.Utility.csproj" />
  </ItemGroup>

</Project>
