<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ITGAdmin.DTO" Version="1.0.2-rc10" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Common.HttpClient\Common.HttpClient.csproj" />
		<ProjectReference Include="..\LCMS.Dto\LCMS.Dto.csproj" />
	</ItemGroup>

</Project>
